# This is a default configuration file
# for the serverless framework.
# For more options and additional customization
# refer to docs.serverless.com
service: the_castel_4153 

provider:
  name: aws
  runtime: python3.7

functions:
  hello:
    handler: handler.hello
    events:
    - http:
        path: /hello
        method: get